export const REQUEST_NAVER_LOGIN = 'REQUEST_NAVER_LOGIN';
export const SUCCESS_NAVER_LOGIN = 'SUCCESS_NAVER_LOGIN';
export const FAIL_NAVER_LOGIN = 'FAIL_NAVER_LOGIN';

export const REQUEST_KAKAO_LOGIN = 'REQUEST_KAKAO_LOGIN';
export const SUCCESS_KAKAO_LOGIN = 'SUCCESS_KAKAO_LOGIN';
export const FAIL_KAKAO_LOGIN = 'FAIL_KAKAO_LOGIN';

export const REQUEST_GOOGLE_LOGIN = 'REQUEST_GOOGLE_LOGIN';
export const SUCCESS_GOOGLE_LOGIN = 'SUCCESS_GOOGLE_LOGIN';
export const FAIL_GOOGLE_LOGIN = 'FAIL_GOOGLE_LOGIN';

export const REQUEST_NAVER_LOGOUT = 'REQUEST_NAVER_LOGOUT';
export const SUCCESS_NAVER_LOGOUT = 'SUCCESS_NAVER_LOGOUT';
export const FAIL_NAVER_LOGOUT = 'FAIL_NAVER_LOGOUT';

export const REQUEST_KAKAO_LOGOUT = 'REQUEST_KAKAO_LOGOUT';
export const SUCCESS_KAKAO_LOGOUT = 'SUCCESS_KAKAO_LOGOUT';
export const FAIL_KAKAO_LOGOUT = 'FAIL_KAKAO_LOGOUT';

export const REQUEST_GOOGLE_LOGOUT = 'REQUEST_GOOGLE_LOGOUT';
export const SUCCESS_GOOGLE_LOGOUT = 'SUCCESS_GOOGLE_LOGOUT';
export const FAIL_GOOGLE_LOGOUT = 'FAIL_GOOGLE_LOGOUT';

export const REQUEST_ADD_POST = 'REQUEST_ADD_POST';
export const SUCCESS_ADD_POST = 'SUCCESS_ADD_POST';
export const FAIL_ADD_POST = 'FAIL_ADD_POST';
